apiVersion: v1
data:
  admin_password: eW91cnBhc3N3b3Jk
  admin_user: YWRtaW4=
  db_password: eW91cnBhc3N3b3Jk
  db_user: YWRtaW4=
  smtp_password: eW91cnBhc3N3b3Jk
  smtp_user: YWRtaW4=
kind: Secret
metadata:
  name: discourse-secret-2b6mh7mh79
type: Opaque
